main: xyz.ravencraft.ThrowableCEggs.Main
name: ThrowableCEggs
version: 1.0
author: kwilk
api-version: 1.13
softdepend: [Vault]
description: Allows players to throw a Creeper Spawn egg and spawn/detonate a creeper upon impact.

commands:
  cegg: